Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('users.urls',namespace='users')),
    path('', include('covid_treker.urls')),
    path('', include('fuzzyexpert.urls')),
    path('', include('fuzzyexpert2.urls')),
    path('', include('consoleapp3.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post, update_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),
    path('blog/<int:id>/update', update_post, name='update_post')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("blogs:blog_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title
    
    

blog/forms.py
from django import forms
from blog.models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model= Post
        fields = ('title','text')
    
    def save_form(self, request, instance, form, change):
        user = request.user 
        instance = form.save(commit=False)
        if not change or not instance.author:
            instance.author = user
        instance.modified_by = user
        instance.save()
        form.save_m2m()
        return instance

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post
from django.utils import timezone
from blog.forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView )
from django.contrib import messages
from django.http import HttpResponseRedirect


# Create your views here.


class PostListView(ListView):
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'
    ordering = ['-created_date']
    model = Post



class PostDetailView(DetailView):
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'
    model = Post


def create_post(request):
    if request.method == 'POST':
        titulli = request.POST.get('title')
        permbajtja = request.POST.get('text')
        postim = Post(title=titulli, text=permbajtja, author=request.user)
        postim.save()
        messages.success(request, f'Публикация была успешно добавлена')
        return redirect('blogs:post_list')
    return render(request, 'blog/create_post.html')

def update_post(request, id):
    # dictionary for initial data with
    # field names as keys
    context ={}
 
    # fetch the object related to passed id
    obj = get_object_or_404(Post, id = id)
 
    # pass the object as instance in form
    form = PostForm(request.POST or None, instance = obj)
 
    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/blog/")
 
    # add form dictionary to context
    context["form"] = form
 
    return render(request, 'blog/update_post.html', context)

def delete_post(request, id):
    Post(id = id).delete()
    return redirect('blogs:post_list')

blog/templates/blog/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h1>Добавить публикацию</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <label for="">Заголовок*</label>
        <input type="text" class="form-control" name="title" placeholder="Заголовок сообщения...">
        <label for="">Описание*</label>
        <textarea class="form-control" name="text" id="" cols="30" rows="10" placeholder="Содержание публикации..."></textarea>
        <br>
        <button class="site-btn">Создать</button>
    </form>

</div>
<br>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-lg-9">
          <h1>Сведения о размещении:</h1>
        <!-- blog post -->
        <div class="blog-post" id="post_det">
          <img src="img/blog/1.jpg" alt="">
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
            </div>
          </div>
          <p><pre>{{ post.text|capfirst }}</pre></p>
          <a href="/blog/" class="btn btn-dark">Вернуться</a>
          {% if request.user.profile.is_teacher == True %}
          <a href="/blog/{{ post.id }}/update" class="btn btn-danger btn-reda">Редактировать</a>
          <a href="/blog/{{ post.id }}/delete" class="btn btn-danger">Удалить Сообщение</a>
          {% endif %}
          <a href="" class="btn btn-danger" id="open_code">Открыть/Закрыть Код</a>
        </div>
        <iframe src="https://swish.swi-prolog.org/" frameborder="0" id="frame"></iframe>
      </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% if request.user.is_authenticated %}
<!-- Page  -->
<section class="blog-page spad pb-0" style="background-image: url(../static/webuni/img/blog_back2.jpg); background-size: cover;" >
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        {% if request.user.profile.is_teacher == True %}
        <a href="{% url 'blogs:create_post' %}" style="color: black;" class="site-btn">Добавить задание</a>
        {% endif %}
        {% if posts %}
        {% for post in posts %}
        <!-- blog post -->
        <div class="blog-post">
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
            </div>
          </div>
          <p><pre>{{ post.text|capfirst }}</pre></p>
          <a href="/blog/{{ post.id }}" class="btn btn-primary">Подробности</a>
        </div>
        {% endfor %}
        {% else %}

        {% endif %}
        
      </div>
      <div class="col-lg-3 col-md-5 col-sm-9 sidebar">
        <div class="sb-widget-item">
          <form class="search-widget">
            <input type="text" placeholder="Поиск">
            <button><i class="fa fa-search"></i></button>
          </form>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title" style="text-align: center;">Архив материалов</h4>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Семестр #1</h4>
          <ul>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Сентябрь</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Октябрь</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Ноябрь</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Декабрь</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Зимняя сессия</h4>
          <ul>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Лекционный материал</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Практический материал</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Дополнительный материал</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Семестр #2</h4>
          <ul>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Февраль</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Март</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Апрель</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Май</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Летняя сессия</h4>
          <ul>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Лекционный материал</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Практический материал</a></li>
            <li><a href="{% static '../static/webuni/download/tasks_archive/' %}" download>Дополнительный материал</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Хэштеги</h4>
          <div class="tags">
            <a href="#">education</a>
            <a href="#">courses</a>
            <a href="#">development</a>
            <a href="#">on-line courses</a>
            <a href="#">prolog</a>
            <a href="#">fuzzy logic</a>
            <a href="#">expert systems</a>
            <a href="#">video lessons</a>
          </div>
        </div>
        <div class="sb-widget-item">
          <div class="add" style="position: fixed; bottom: 10px; right: 10px;">
            <a href="#"><img src="../static/webuni/img/up_line.png" width="200" height="200" alt=""></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->
{% endif %}
{% endblock content %}

blog/templates/blog/update_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if request.user.profile.is_teacher == True %}
<div class="container">
    <div class="row">
      <div class="col-lg-9">
          <h1>Редактировать размещение:</h1>
        <!-- blog post -->
        <div class="blog-post" id="redact">
              <!-- Create a Form -->
              <form method="POST">
                  <!-- Security token by Django -->
                  {% csrf_token %}
                  <!-- form as paragraph -->
                  {{ form.as_p }}
                  <input type="submit" value="Редактировать" class="btn-red">
              </form>
        </div>
      </div>
  </div>
</div>
{% endif %}
{% endblock content %}