Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('users.urls',namespace='users')),
    path('', include('covid_treker.urls')),
    path('', include('fuzzyexpert.urls')),
    path('', include('fuzzyexpert2.urls')),
    path('', include('consoleapp3.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post, update_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),
    path('blog/<int:id>/update', update_post, name='update_post')
]

consoleapp3/urls.py
from django.urls import path
from . import views

app_name = 'consoleapp3'

urlpatterns = [
    path('consoleapp/', views.start, name="start" ),
    path('consoleapp/about', views.about, name="about" )
]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,CourseListView, CourseDetailView,LessonDetailView, SearchView, create_group, create_course, create_lesson

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', create_group, name='krijo_klase'),
    path('krijo/lende', create_course, name='krijo_lende'),
    path('krijo/mesim', create_lesson, name='krijo_mesim')
]

fuzzyexpert/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'fuzzyexpert'

urlpatterns = [
    path('main_form/', views.index, name='covid_main'),
    path('main_form/res', views.result, name='result'),
    path('main_form/c19',views.c19,name='covid19')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import Profile, teacher

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),
    path('kerkesa/', teacher, name='kerkesa')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
	<title>Дистанционное обучение</title>
	<meta charset="UTF-8">
	<meta name="description" content="Education">
	<meta name="keywords" content="education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'webuni/img/favicon.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
	<link rel="stylesheet" href="{% static 'webuni/css/base-page.css'%}"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav">
		<div class="container">
		  <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static 'webuni/img/logo.png' %}" alt=""></a>
		  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Меню
		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto topmenu">
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}">О проекте</a>
			  </li>
			  {% if request.user.is_authenticated %}
			  <li class="nav-item mx-0 mx-lg-1 multi">
			  	<a href="" class="submenu-link">Лучшие Проекты</a>
			  	<ul class="submenu">
			  		<li><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'covid_treker:statistic' %}">covid19 traker</a></li>
					<li><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'fuzzyexpert:covid_main' %}">covid expert</a></li>
					<li><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'fuzzyexpert2:study_form' %}">study expert</a></li>
					<li><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'consoleapp3:start' %}">fuzzy controller</a></li>
				</ul>
			  </li>
			  {% endif %}
			  <li class="nav-item mx-0 mx-lg-1">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#kurset">Курсы</a>
				  </li>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'blogs:post_list' %}">Задания</a>
			  </li>
			  {% if request.user.profile.is_teacher == True %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_klase' %}">Cоздание группы</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_lende' %}">Cоздание курса</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_mesim' %}">Создание занятия</a>
			  </li>

			  {% endif %}
			  {% if request.user.is_authenticated %}
			  
			  <div class="dropdown show">
				<a class=" dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded js-scroll-triggeraa" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{request.user.username}}
				</a>
			  
				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				  <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
				  <a class="dropdown-item" href="{% url 'account_logout' %}">Выйти</a>
				</div>
			  </div>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_login' %}">Войти</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_signup' %}">Регистрация</a>
			  </li>
              {% endif %}
			</ul>
		  </div>
		</div>
	  </nav>

{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}

{% if request.user.is_authenticated %}
{% else %}
	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Присоединяйтесь к нашему сообществу!</h2>
				<p>Получите доступ ко всему материалу в виде онлайн-лекции и практических заданий, 
	а также изучите и освоите знания с помощью видео и общения с учителями и другими участниками сообщества. 
Это очень просто, единственное, что вам нужно сделать, это зарегистрироваться. Нажмите ниже: </p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Зарегистририроваться</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->
{% endif %}


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Контактная информация</h4>
						<ul class="contact-list">
							<li>Russia<br>Republic of Tatarstan<br>Kazan</li>
							<li>serejenbka@inbox.ru</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Состав студентов и преподавателей</h4>
						<ul>
							<li><a href="https://kpfu.ru/computing-technology/sotrudniki">Преподаватели</a></li>
							<li><a href="https://admissions.kpfu.ru/priem-v-universitet/prikazy-o-zachislenii-2021">Студенты</a></li>
							
						</ul>
					</div>
					<div class="widget-item">
						<h4>Социальные сети</h4>
						<ul>
							<li><a href="https://www.youtube.com/channel/UCuBpmT5U9L56tpog6SMoH9w/videos">YouTube</a></li>
							<li><a href="https://vk.com/ivmiit">VKontakte</a></li>
							<li><a href="https://t.me/kznuniversity">Telegram</a></li>
							<li><a href="https://www.instagram.com/kazanfederaluniversity/">Instagram</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Кабинет преподавателя</h4>
						<ul>
							<li><a href="admin/">Посетить</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<div class="btm">
					Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved.
				</div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
	<script src="{% static 'webuni/js/freelancer.js' %}"></script>
	<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
	document.getElementById('open_code').addEventListener('click', function(e) {
	   e.preventDefault();
		var obj1 = document.getElementById('frame');
		if (obj1.style.display == 'none') {
			document.getElementById('frame').style.display = "block";
		}
		else {
			document.getElementById('frame').style.display = "none";
		}
	}, false);
  </script>
</html>

templates/console_main.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Нечёткий Логический Контроллер</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="{% static 'webuni/css/all.min.css'%}" />
    <link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'webuni/css/templatemo-style.css'%}" />

  </head>
  <body>
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'webuni/img/console/bg-01.jpg' %}">
      <div class="container-fluid">
        <div class="row tm-brand-row">
          <div class="col-lg-4 col-11">
            <div class="tm-brand-container tm-bg-white-transparent">
              <div class="tm-brand-texts">
                <h1 class="text-uppercase tm-brand-name" align="center">Fuzzy Logic</h1>
                <p class="small"></p>
              </div>
            </div>
          </div>
          <div class="col-lg-8 col-1">
            <div class="tm-nav">
              <nav class="navbar navbar-expand-lg navbar-light tm-bg-white-transparent tm-navbar">
                <button class="navbar-toggler" type="button"
                  data-toggle="collapse" data-target="#navbarNav"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% url 'courses:home' %}">Главная</a>
                    </li>
                    <li class="nav-item active">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="#">Введение <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% url 'consoleapp3:about' %}">Демонстрация</a>
                    </li>
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% static 'webuni/download/FuzzyLogicController.exe' %}" download><strong class="download">Скачать</strong></a>
                    </li>
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                        <a class="nav-link" href="{% static 'webuni/download/statements/fuzzy_controller_otchet.docx' %}" download><img src="{% static 'webuni/img/otchet_blue.png' %}" width="100" height="50" alt="Отчёт" title="Скачать Отчёт"></a>
                    </li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>

        <section class="row" id="tmHome">
          <div class="col-12 tm-home-container">
            <div class="text-white tm-home-left">
              <p class="text-uppercase tm-slogan"> Приложение с графическим интерфейсом (GUI) на Python</p>
              <hr class="tm-home-hr" />
              <h2 class="tm-home-title">Fuzzy Logic Controller</h2>
              <p class="tm-home-text">
                Разработка симулятора движения с графическим интерфейсом на основе нечёткого логического контроллера (нечёткого регулятора)
              </p>
              <a href="#tmFeatures" class="btn btn-primary">Подробнее</a>
            </div>
            <div class="tm-home-right">
              <img src="{% static 'webuni/img/console/screen_demo1.jpg' %}" width="600" height="420" alt="App Demonstration" />
            </div>
          </div>
        </section>

        <!-- Features -->
        <div class="row" id="tmFeatures">
          <div class="col-lg-4">
            <div class="tm-bg-white-transparent tm-feature-box">
            <h3 class="tm-feature-name">Создание карт</h3>
            
            <div>
                <img src="{% static 'webuni/img/console/map_demo.jpg' %}" width="200" height="200" alt="Map" />
            </div>

            <p class="text-center">Вы можете создать карту, по которой будет перемещаться движущийся объект</p>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="tm-bg-white-transparent tm-feature-box">
                <h3 class="tm-feature-name">Разнообразие карт</h3>

                <div>
                    <img src="{% static 'webuni/img/console/map_select.jpg' %}" width="200" height="100" alt="Map" />
                </div>
                <br>
                <p class="text-center">Вы можете менять карту, не выходя из приложения
                </p>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="tm-bg-white-transparent tm-feature-box">
                <h3 class="tm-feature-name">Множество параметров</h3>

                <div>
                    <img src="{% static 'webuni/img/console/parametrs.jpg' %}" width="250" height="150" alt="Map" />
                </div>
                <p class="text-center"> Вы можете задать параметры для Гауссовской функции распределения и Нечётких правил
                </p>
            </div>
          </div>
        </div>
        <!-- Call to Action -->
        <section class="row" id="tmCallToAction">
          <div class="col-12 tm-call-to-action-col">
            <img src="{% static 'webuni/img/console/call_email.gif' %}" alt="Image" class="img-fluid tm-call-to-action-image" />
            <div class="tm-bg-white tm-call-to-action-text">
              <h2 class="tm-call-to-action-title">Контактная информация</h2>
              <p class="tm-call-to-action-description">
                Если у Вас остались вопросы касательно возможностей приложения или Вы хотите следить за последними обновлениями приложения, то можете отправить на почту сообщение с Вашей просьбой, Пожеланием или Отзывом! 
              </p>
              <p class="tm-call-to-action-form"><a href="mailto:serejenbka@inbox.ru&body= Здравствуйте, Сергей Васильевич!?subject=Fuzzy Logic Controller"><img src="{% static 'webuni/img/console/btn_send.gif' %}" width="190" height="90"></a></p>
            </div>
          </div>
        </section>

        <!-- Page footer -->
        <footer class="row">
          <p class="col-12 text-white text-center tm-copyright-text">
            Copyright &copy; 2022. 
            Created and Designed by <a href="https://vk.com/sergei_karp" class="tm-copyright-link">Sergey Karpov</a>
          </p>
        </footer>
      </div>
      <!-- .container-fluid -->
    </div>

    <script src="{% static 'webuni/js/jquery.min.js'%}"></script>
    <script src="{% static 'webuni/js/parallax.min.js'%}"></script>
    <script src="{% static 'webuni/js/bootstrap.min.js'%}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/bg.jpg'%}">
  <div class="container">
    <div class="hero-text text-white">
      {% if request.user.is_authenticated %}
      <h2>Добро пожаловать {% if request.user.profile.is_teacher == True %}
         преподаватель,
        {% endif %} {{ request.user.username|capfirst }}

       
      </h2>
      {% else %}
      <h2>Web-платформа для обучения логическому языку программирования Prolog</h2>
      {% endif %}
      <p></p>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="Что ищете?">
          <button type="submit" class="site-btn">Поиск</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2 id="kurset">Обучающие Курсы</h2>
      <p>Курсы делятся на разные категории в зависимости от уровня. Вы должны сначала зарегистрироваться, а затем сможете посещать курсы, к которым вы принадлежите.</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div data-aos="zoom-in" class="col-lg-4 col-md-6">
        <div class="categorie-item">
          <div class="ci-thumb set-bg" data-setbg="{{ cat.photo.url }}"></div>
          <div class="ci-text">

            <h5>{{cat.title|capfirst}}</h5>

            <p>{{ cat.description|capfirst }}</p>
            <span><a class="btn btn-success" href="/courses/{{ cat.id }}">Подробнее</a></span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->
{% if request.user.is_authenticated %}
{% else %}
<section class="course-section spad">
  <div class="container">
    <div class="section-title mb-0">
      <h2>Примеры курсов</h2>
      <p class="pb-3">Вот некоторые примеры курсов, которые студенты и ученики проходят на нашей платформе.</p>
    </div>
  </div>
  <div class="course-warp">                                     
    <div class="row course-items-area">
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 design">
        <div class="course-item">
          <div class="course-thumb set-bg">
            <video width="100%" height="290" controls="controls">
              <source src="{% static 'webuni/videos/homepage/1.mp4' %}" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
              Тег video не поддерживается вашим браузером.
            </video>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>SWI Prolog</h5>
              <p>Introduction</p>
              <div class="students">Course 1</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/0.jpg' %}"></div>
              <p>Sergey Karpov, <span>Student</span></p>
            </div>
          </div>
        </div>
      </div>
      <div class="mix col-lg-3 col-md-4 col-sm-6 design">
        <div class="course-item">
          <div class="course-thumb set-bg">
            <video width="100%" height="290" controls="controls">
              <source src="{% static 'webuni/videos/homepage/2.mp4' %}" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
              Тег video не поддерживается вашим браузером.
            </video>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>SWI Prolog</h5>
              <p>Part 2</p>
              <div class="students">Course 2</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/0.jpg' %}"></div>
              <p>Sergey Karpov, <span>Student</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 web">
        <div class="course-item">
          <div class="course-thumb set-bg">
            <video width="100%" height="290" controls="controls">
              <source src="{% static 'webuni/videos/homepage/3.mp4' %}" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
              Тег video не поддерживается вашим браузером.
            </video>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>SWI Prolog</h5>
              <p>Part 2</p>
              <div class="students">Course 2</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/0.jpg' %}"></div>
              <p>Sergey Karpov, <span>Student</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 photo">
        <div class="course-item">
          <div class="course-thumb set-bg">
            <video width="100%" height="290" controls="controls">
              <source src="{% static 'webuni/videos/homepage/4.mp4' %}" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
              Тег video не поддерживается вашим браузером.
            </video>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>SWI Prolog</h5>
              <p>Part 3</p>
              <div class="students">Course 2</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/0.jpg' %}"></div>
              <p>Sergey Karpov, <span>Student</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endif %}
<!-- course section end -->

{% if request.user.is_authenticated %}

<!-- signup section -->
{% if request.user.profile.is_teacher == True %}
<section class="middle-section">
<div class="container">
  <h1 class="text-center">В вашей учетной записи есть доступ к преподавателю</h1>
  <p class="text-center">Имея учетную запись преподавателя, вы теперь имеете полный доступ к этой платформе. Вы можете выполнять больше функций, чем первоначальная учетная запись студента. Вот некоторые из этих функций:</p>

  <div data-aos="fade-right" class="row mt-4 mb-4 bg-light in">
    <div class="col-md-4 text-center">
      <h3 class="p-4">Вы можете создать собственные группы</h3> 
      <a href="{% url 'courses:krijo_klase' %}" class="btn btn-outline-primary m-4">Создать группу</a>
    </div>
    <div class="col-md-8">
      <img class="img-fluid w-100" src="{% static 'webuni/img/categories/4.jpg' %}" alt="">
    </div>
  </div>

  <div data-aos="fade-left" class="row mt-4 mb-4 bg-light in">
      <div class="col-md-8">
        <img class="img-fluid w-100" src="{% static 'webuni/img/categories/2.jpg' %}" alt="">
      </div>
  
    <div class="col-md-4 text-center">
      <h3 class="p-4">Вы можете создавать новые курсы</h3> 
      <a href="{% url 'courses:krijo_lende' %}" class="btn btn-outline-primary m-4">Добавить курс</a>
  </div>
</div>

<div data-aos="fade-right" class="row mt-4 mb-4 bg-light in">
  <div class="col-md-4 text-center">
    <h3 class="p-4">Вы можете загружать новые занятия</h3> 
    <a href="{% url 'courses:krijo_mesim' %}" class="btn btn-outline-primary m-4">Загрузить занятие</a>
  </div>
  <div class="col-md-8">
    <img class="img-fluid w-100" src="{% static 'webuni/img/categories/1.jpg' %}" alt="">
  </div>
</div>
</div>
</section>

{% else %}
<section data-aos="zoom-out" class="signup-section spad">
  <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            <h2>Зарегистрироваться в качестве преподавателя</h2>
            <p>Чтобы зарегистрироваться в качестве преподавателя на платформе, вы должны заполнить следующие поля, и тогда у вас будет полный доступ к загрузке курсов и видео.</p>
            
          </div>
          <!-- signup form -->
          <form action="/kerkesa/" method="post" class="signup-form">{% csrf_token %}
            <input type="text" placeholder="Ваше имя" name="name">
            <input type="text" placeholder="E-mail" name="e-mail">
            <input type="text" placeholder="Номер телефона" name="phone">
            <button class="site-btn">Отправить запрос</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endif %}
<!-- signup section end -->
{% else %}
{% endif %}

{% endblock content %}